services:
  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Auth.API/Dockerfile
    networks:
      - sdts_SDTS

networks:
  sdts_SDTS:
    external: true