version: "3"
services:
  userapi_build:
    image: userservice
    build:
      context: ./
      dockerfile: Dockerfile_UserAPI
    environment:
      - ConsulRegisterOptions__Port=5002
      - ConsulRegisterOptions__Ip=userservice1
      #- Redis_Multiplexer=some-redis:6379
    ports:
      - 5010:5000
      - 5020:5001
      - 5030:5002
    restart: always
    container_name: userservice1

  userapi2:
    image: userservice
    environment:
      - ConsulRegisterOptions__Port=5002
      - ConsulRegisterOptions__Ip=userservice2
      #- Redis_Multiplexer=some-redis
    ports:
      - 5040:5000
      - 5050:5001
      - 5060:5002
    restart: always
    container_name: userservice2
    depends_on:
      - userapi_build
      
  userapi3:
    image: userservice
    environment:
      - ConsulRegisterOptions__Port=5002
      - ConsulRegisterOptions__Ip=userservice3
      #- Redis_Multiplexer=some-redis
    ports:
      - 5070:5000
      - 5080:5001
      - 5090:5002
    restart: always
    container_name: userservice3
    depends_on:
      - userapi_build

  useraggre_build:
    image: useraggre
    build:
      context: ./
      dockerfile: Dockerfile_UserAggre
    environment:
      - ConsulRegisterOptions__Port=5100
      - ConsulRegisterOptions__Ip=useraggre1
    ports:
      - 5100:5100
      - 5110:6100
    restart: always
    container_name: useraggre1
    
  useraggre2:
    image: useraggre
    environment:
      - ConsulRegisterOptions__Port=5100
      - ConsulRegisterOptions__Ip=useraggre2
    ports:
      - 5120:5100
      - 5130:6100
    restart: always
    container_name: useraggre2
    depends_on:
      - useraggre_build
    
  usergateway_build:
    image: usergateway
    build:
      context: ./
      dockerfile: Dockerfile_UserGateWay
    container_name: usergateway1
    ports:
      - 5200:80
      - 5210:443
    restart: always
    environment:
      - AuthUrl=http://userauth:80
     
  usergateway2:
    image: usergateway
    container_name: usergateway2
    ports:
      - 5220:80
      - 5230:443
    restart: always
    depends_on:
      - usergateway_build
    environment:
      - AuthUrl=http://userauth:80
      
  userauth_build:
    image: userauth
    build:
      context: ./
      dockerfile: Dockerfile_UserAuth
    ports:
      - 5400:80
    container_name: userauth
    restart: always
  